[package]
name = "vnext"
version = "0.0.0-dev"
edition = "2021"

[dependencies]
serde_json = "1.0"
clap = { version = "4.5.31", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
fern = "0.7.1"
include_dir = "0.7.4"
log = "0.4.26"
git2 = "0.19.0"
semver = "1.0.23"