name: On Push to Main, Version and Tag For Release
on:
  push:
    branches:
    - main

permissions:
  packages: write
  contents: write

jobs:
  quality:
    uses: harmony-labs/workflow-rust/.github/workflows/quality.yaml@main
    with:
      lint: false

  # This uses commit logs and tags from git to determine the next version number and create a tag for the release
  # Some commits such are chore: will not trigger a version bump and tag! This is by design.
  version-and-tag:
    name: Version and Tag
    needs: quality
    uses: harmony-labs/workflow-release/.github/workflows/version-and-tag.yaml@1bccc20b92d12905990b8d24b22ce81564a08f44 # v1.0.0
    secrets: inherit
    with:
      useDeployKey: true
      rust: true