name: On Version Tagged, Build and Publish Rust Binaries
on:
  push:
    tags:
    - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    uses: harmony-labs/workflows-rust/.github/workflows/release.yaml@v0.2.1
    with:
      binary_name: ${{ github.event.repository.name }}
